name = "wincc cards"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages"

[[pages_build_output.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production.vars]
NODE_ENV = "production"