name = "winccards-nextsjs-voice"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-08-17"  # today’s date
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages"

[[pages_build_output.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production.vars]
NODE_ENV = "production"